accounts/urls.py
from django.contrib import auth
from django.urls import path, include

from . import views

app_name = 'Accounts'

urlpatterns = [
    path('',  include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"),
]

books/urls.py
from django.urls import path

from . import views

app_name = 'Books'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name="create"),
    path('edit/<int:book_id>', views.update, name="edit"),
    path('delete/<int:book_id>', views.delete, name="delete"),
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', namespace="Books")),
    path('accounts/', include('accounts.urls', namespace="Accounts")),
]

accounts/models.py
from django.db import models

# Create your models here.

books/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models


class ISBN(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author_title = models.CharField(max_length=100)
    book_title = models.CharField(max_length=255)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.id}"


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    name = models.CharField(max_length=50)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=4096)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    categories = models.ManyToManyField(Category)
    ISBN = models.OneToOneField(ISBN, null=True, blank=True, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from books.models import Book


class CategoryForm(ModelForm):
    def clean(self):
        super().clean()

        name = self.cleaned_data.get("name")
        if len(name) < 2:
            raise ValidationError("Category Must be at least 2 characters.")


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ('ISBN', )

    def clean_title(self):
        title: str = self.cleaned_data.get("title")

        if not 10 <= len(title) <= 50:
            raise ValidationError("Title must be between 10 and 50 characters.")

        return title

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


# Create your views here.

def register(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        if user := authenticate(username=username, password=password):
            login(request, user)
            return redirect("/books")

    return render(request, "registration/register.html", {"form": form})

books/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect

from books.forms import BookForm
from books.models import Book


@login_required
@permission_required(['books.view_book'])
def index(request):
    books = Book.objects.all()
    return render(request, 'books/index.html', {"books": books})


@login_required
@permission_required(['books.add_book'])
def create(request):
    book_form = BookForm(request.POST or None)
    if book_form.is_valid():
        book_form.save()
        return redirect("Books:index")

    return render(request, "books/create.html", {"form": book_form})


@login_required
@permission_required(['books.change_book'])
def update(request, book_id):
    book = Book.objects.get(pk=book_id)
    book_form = BookForm(request.POST or None, instance=book)
    if book_form.is_valid():
        book_form.save()
        return redirect("Books:index")

    return render(request, "books/edit.html", {"form": book_form, "book_id": book.pk})


@login_required
@permission_required(['books.delete_book'])
def delete(request, book_id):
    Book.objects.get(pk=book_id).delete()
    return redirect("Books:index")

books/templates/books/create.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="row">
        <form method="POST" action="{% url 'Books:create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
{% endblock %}

books/templates/books/edit.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="row">
        <form method="POST" action="{% url 'Books:edit' book_id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
    </div>
{% endblock %}

books/templates/books/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>Books available</h1>
    {% if perms.books.create_book %}
        <a href="{% url 'Books:create' %}">Create New Book</a>
    {% endif %}
    <div class="row">
        {% for book in books %}
            <div class="col">
                <div><span class="bold">Book Title: </span>{{ book.title }}</div>
                <div><span class="bold">Book Name: </span>{{ book.content }}</div>
                {% if perms.books.edit_book %}
                    <a href="{% url 'Books:edit' book.id %}">Edit Book</a>
                {% endif %}
                {% if perms.books.delete_book %}
                    <a href="{% url 'Books:delete' book.id %}">Delete Book</a>
                {% endif %}

            </div>
            <hr>
        {% empty %}
            <center>No Books Available</center>
        {% endfor %}
    </div>
{% endblock %}

books/templates/layouts/books.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block styles %}{% endblock %}
    <title>{% block title %}Books{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
{% block scripts %}{% endblock %}
</body>
</html>

templates/layouts/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block styles %}{% endblock %}
    <title>{% block title %}Books{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
    <div class="row">
        <a href="{% url 'Accounts:logout' %}">Logout</a>
    </div>
{% endif %}
<div class="container">
    {% block content %}{% endblock %}
</div>
{% block scripts %}{% endblock %}
</body>
</html>